# Generated by Django 3.2.3 on 2021-06-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='base',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='indicacao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ingredientes',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='mododeuso',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='precaucoes',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='utilidade',
        ),
    ]
