# Generated by Django 3.2.3 on 2021-05-29 14:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('facial', 'Facial'), ('corpo', 'Corpo'), ('cabelos', 'Cabelos')], max_length=100, verbose_name='Categoria')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('base', models.CharField(max_length=200, verbose_name='Base')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('caracteristicas', models.TextField(verbose_name='Características')),
                ('indicacao', models.TextField(verbose_name='Indicação')),
                ('utilidade', models.TextField(verbose_name='Utilidade')),
                ('ingredientes', models.TextField(verbose_name='Ingredientes')),
                ('mododeuso', models.TextField(verbose_name='Modo de Uso')),
                ('precaucoes', models.TextField(verbose_name='Precauções')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('P', 'Pedido realizado'), ('F', 'Fazendo'), ('E', 'Saiu para entrega')], max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app.cliente')),
                ('produtos', models.ManyToManyField(to='app.Produto')),
            ],
        ),
    ]
