# Generated by Django 3.2.3 on 2021-06-10 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('completo', models.BooleanField(default=False, null=True, verbose_name='Completo')),
                ('id_transacao', models.CharField(max_length=200, null=True, verbose_name='ID da transação')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('facial', 'Facial'), ('corpo', 'Corpo'), ('cabelos', 'Cabelos')], max_length=100, verbose_name='Categoria')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('base', models.CharField(max_length=200, verbose_name='Base')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('caracteristicas', models.TextField(verbose_name='Características')),
                ('indicacao', models.TextField(verbose_name='Indicação')),
                ('utilidade', models.TextField(verbose_name='Utilidade')),
                ('ingredientes', models.TextField(verbose_name='Ingredientes')),
                ('mododeuso', models.TextField(verbose_name='Modo de Uso')),
                ('precaucoes', models.TextField(verbose_name='Precauções')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade')),
                ('data_add', models.DateTimeField(auto_now_add=True, verbose_name='Data da Adição')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.pedido', verbose_name='Pedido')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.produto', verbose_name='Produto')),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=200, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=200, verbose_name='Estado')),
                ('cep', models.CharField(max_length=200, verbose_name='CEP')),
                ('data_add', models.DateTimeField(auto_now_add=True, verbose_name='Data da Adição')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cliente', verbose_name='Cliente')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.pedido', verbose_name='Pedido')),
            ],
        ),
    ]
