# Generated by Django 3.2.3 on 2021-06-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_enderecoentrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor'),
        ),
    ]
